service: '${self:custom.project}-${self:custom.function}-lambda'

custom:
  # project specific variables
  vars: ${file(./variables.json)}
  infoVars: ${file(./aws_infra_parameters.json)}
  resourceVars: ${file(./aws_resource_parameters.json)}
  commonVars: ${file(./lambda_common_env_parameters.json)}
  region: ${env:AWS_REGION}
  environment: ${env:ENVIRONMENT}
  stage: ${env:ENVIRONMENT}
  buildNumber: ${env:CI_PIPELINE_IID}
  project: ${env:PROJECT_CODE}
  APIGWAFV2: ${self:custom.resourceVars.apiWafv2}
  function: auth
  kmsArn:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-kms-arn'
  customDomainName:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
  customDomainPath: !Sub ${env:PROVIDER}-${self:custom.vars.releaseVersion}
  apiauthorizerArn:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-apiauthorizer'
  deploy_bucket: ${env:DEPLOY_S3_BUCKET}
  cloudWatchRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/cochlear-general-apigateway-log-role'
  secretName:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-serverless-secret-name'
  redisHostname:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-url'
  redisPort:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-port'
  redisSG:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-security-group'

  # serverless plugins specific variables
  logRetentionInDays: 30
  apiStageTags:
    Owner: ${self:custom.vars.Owner}
    Description: ${self:custom.vars.Description}
    Name: ${self:custom.project}-${self:custom.function}-lambda
    Function: Serverless
    Environment: ${self:custom.environment}
    Product: ${self:custom.vars.Product}
    Resource: DRX
  apigwBinary:
    types: #list of mime-types
      - '*/*'
  prune:
    automatic: true
    number: 3
  associateWaf:
    name: ${self:custom.APIGWAFV2}
    version: V2

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.region}
  vpc:
    securityGroupIds:
      - ${self:custom.redisSG}
    subnetIds: ${self:custom.infoVars.subnets}
  endpointType: regional
  stage: ${self:custom.stage}
  deploymentBucket:
    name: ${self:custom.deploy_bucket} # Deployment bucket name. Default is generated by the framework
    serverSideEncryption: AES256 # when using server-side encryption
  memorySize: 1024
  timeout: 29
  logs:
    restApi:
      roleManagedExternally: true
      role: ${self:custom.cloudWatchRole}
  stackTags:
    Owner: ${self:custom.vars.Owner}
    project: ${self:custom.project}
    Resource: DRX
  tags:
    Description: ${self:custom.vars.Description}
    Name: '${self:custom.project}-${self:custom.function}'
    Function: 'Serverless'
    Environment: ${self:custom.environment}
    Product: ${self:custom.vars.Product}
    buildNumber: ${self:custom.buildNumber}
  tracing:
    apiGateway: true
    lambda: true
  apiGateway:
    disableDefaultEndpoint: true
  environment:
    AWS_APPCONFIG_EXTENSION_POLL_INTERVAL_SECONDS: 30
    AWS_APPCONFIG_EXTENSION_POLL_TIMEOUT_MILLIS: 3000
    AWS_APPCONFIG_EXTENSION_HTTP_PORT: 2772

plugins:
  - serverless-plugin-optimize
  - api-gateway-stage-tag-plugin
  - serverless-plugin-log-retention
  - serverless-prune-plugin
  - ./serverless-plugin/metric
  - serverless-associate-waf

package: # Optional deployment packaging configuration
  individually: true
  include: # Specify the directories and files which should be included in the deployment package
    - src/**

functions:
  CorsLoginFunction:
    handler: src/cors-handler.handleRequest
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      corsAllowedHeaders: ${self:custom.commonVars.corsAllowedHeaders}
      corsAllowedMethods: ${self:custom.commonVars.corsGETAllowedMethods}
      corsOrigin: ${self:custom.commonVars.corsOrigin}
      corsMaxAge: ${self:custom.commonVars.corsMaxAge}
    role: lambdaRole
    events:
      - http:
          path: /authorize
          method: OPTIONS
  CorsTokenRevokeFunction:
    handler: src/cors-handler.handleRequest
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      corsAllowedHeaders: ${self:custom.commonVars.corsAllowedHeaders}
      corsAllowedMethods: ${self:custom.commonVars.corsPOSTAllowedMethods}
      corsOrigin: ${self:custom.commonVars.corsOrigin}
      corsMaxAge: ${self:custom.commonVars.corsMaxAge}
    role: lambdaRole
    events:
      - http:
          path: /token
          method: OPTIONS
      - http:
          path: /revoke
          method: OPTIONS
  login:
    handler: src/handler.login
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      auth0CustomDomain: ${self:custom.vars.auth0CustomDomain}
      auth0Host: ${self:custom.vars.auth0Host}
      auth0AuthorizePath: ${self:custom.vars.auth0AuthorizePath}
      auth0ClientId: ${self:custom.vars.auth0ClientId}
      auth0Audience: ${self:custom.vars.auth0Audience}
      auth0ProfessionalApps: ${self:custom.vars.auth0ProfessionalApps}
      auth0RecipientConnectionName: ${self:custom.vars.auth0RecipientConnectionName}
      auth0ProfessionalConnectionName: ${self:custom.vars.auth0ProfessionalConnectionName}
      callback_url: ${self:custom.vars.callback_url}
      secretName: ${self:custom.secretName}
      logLevel: ${self:custom.vars.logLevel}
      DRXBaseUrl: ${self:custom.vars.DRXBaseUrl}
      DRXGetAccountPath: ${self:custom.vars.DRXGetAccountPath}
    role: lambdaRole
    events:
      - http:
          path: /authorize
          method: get
          cors:
            origins: '*'
            headers:
              - Content-Type
              - x-api-token
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - authorizationtoken
              - Location
              - Access-Control-Allow-Origin

  token:
    handler: src/handler.getToken
    layers:
      - arn:aws:lambda:ap-southeast-2:080788657173:layer:AWS-AppConfig-Extension:91
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      environment: ${self:custom.environment}
      region: ${self:custom.region}
      secretName: ${self:custom.secretName}
      boomiOauthEndpoint: ${self:custom.commonVars.boomiOauthEndpoint}
      boomiServiceEndpoint: ${self:custom.commonVars.boomiServiceEndpoint}
      SFClientID: ${self:custom.commonVars.sfClientID}
      auth0CustomDomain: ${self:custom.vars.auth0CustomDomain}
      auth0Host: ${self:custom.vars.auth0Host}
      auth0TokenPath: ${self:custom.vars.auth0TokenPath}
      auth0ClientId: ${self:custom.vars.auth0ClientId}
      auth0Audience: ${self:custom.vars.auth0Audience}
      callback_url: ${self:custom.vars.callback_url}
      RedisPort: ${self:custom.redisPort}
      RedisHostname: ${self:custom.redisHostname}
      publicKey: ${self:custom.vars.publicKey}
      userSessionSeconds: ${self:custom.vars.userSessionSeconds}
      userSessionPrefix: ${self:custom.commonVars.userSessionPrefix}
      logLevel: ${self:custom.vars.logLevel}
      DRXBaseUrl: ${self:custom.vars.DRXBaseUrl}
      DRXGetAccountPath: ${self:custom.vars.DRXGetAccountPath}
      appConfigApplicationId: ${self:custom.vars.appConfigApplicationId}
      appConfigEnvironmentId: ${self:custom.vars.appConfigEnvironmentId}
      appConfigUrl: ${self:custom.vars.appConfigUrl}
    role: lambdaRole
    events:
      - http:
          path: /token
          method: post
          request:
            schemas:
              application/json: ${file(token-post.yml)}
          cors:
            origins: '*'
            headers:
              - Content-Type
              - x-api-token
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - authorizationtoken

  revoke:
    handler: src/handler.revokeToken
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      secretName: ${self:custom.secretName}
      auth0CustomDomain: ${self:custom.vars.auth0CustomDomain}
      auth0Host: ${self:custom.vars.auth0Host}
      auth0ClientId: ${self:custom.vars.auth0ClientId}
      auth0RevokePath: ${self:custom.vars.auth0RevokePath}
      blacklistSeconds: ${self:custom.vars.blacklistSeconds}
      RedisPort: ${self:custom.redisPort}
      RedisHostname: ${self:custom.redisHostname}
      publicKey: ${self:custom.vars.publicKey}
      userSessionSeconds: ${self:custom.vars.userSessionSeconds}
      userSessionPrefix: ${self:custom.commonVars.userSessionPrefix}
      logLevel: ${self:custom.vars.logLevel}
    role: lambdaRole
    events:
      - http:
          path: /revoke
          method: post
          request:
            schemas:
              application/json: ${file(revoke-post.yml)}
          cors:
            origins: '*'
            headers:
              - Content-Type
              - x-api-token
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - authorizationtoken

## Resources ##
resources:
  Resources:
    CustomDomainMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn:
        - 'ApiGatewayDeployment${sls:instanceId}'
      Properties:
        RestApiId: !Ref ApiGatewayRestApi
        BasePath: ${self:custom.customDomainPath}
        DomainName:
          ${self:custom.customDomainName}
          # 'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
        Stage: ${self:custom.stage}

    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /drx/all/
        PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/core/PermissionsBoundary'
        ManagedPolicyArns:
          [
            'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole',
            'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
          ]
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaDRX
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # Default Lambda Permissions for Cloudwatch Log Access
                  Resource: arn:aws:logs:${self:custom.region}:*:log-group:/aws/lambda/*:*:*
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                - Effect: Allow
                  Resource:
                    - arn:aws:ssm:${self:custom.region}:*:parameter/*
                  Action:
                    - ssm:GetParameter
                - Effect: Allow
                  Resource:
                    - arn:aws:secretsmanager:${self:custom.region}:*:*
                  Action:
                    - secretsmanager:GetSecretValue
                - Effect: 'Allow'
                  Resource:
                    - !Sub
                      - 'arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/${ApplicationId}/environment/${EnvironmentId}/configuration/*'
                      - ApplicationId: ${self:custom.vars.appConfigApplicationId}
                        EnvironmentId: ${self:custom.vars.appConfigEnvironmentId}
                  Action:
                    - appconfig:GetLatestConfiguration
                    - appconfig:StartConfigurationSession
  Outputs:
    RestApiId:
      Description: 'rest api id'
      Value:
        Ref: ApiGatewayRestApi
