service: '${self:custom.project}-${self:custom.function}-lambda'

custom:
  # project specific variables
  vars: ${file(./variables.json)}
  infoVars: ${file(./aws_infra_parameters.json)}
  resourceVars: ${file(./aws_resource_parameters.json)}
  commonVars: ${file(./lambda_common_env_parameters.json)}
  region: ${env:AWS_REGION}
  environment: ${env:ENVIRONMENT}
  stage: ${env:ENVIRONMENT}
  buildNumber: ${env:CI_PIPELINE_IID}
  project: ${env:PROJECT_CODE}
  APIGWAFV2: ${self:custom.resourceVars.apiWafv2}
  function: cache-refresh
  kmsArn:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-kms-arn'

  customDomainName:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
  customDomainPath: !Sub ${env:PROVIDER}-${self:custom.vars.releaseVersion}
  apiauthorizerArn:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-apiauthorizer'
  deploy_bucket: ${env:DEPLOY_S3_BUCKET}
  cloudWatchRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/cochlear-general-apigateway-log-role'
  redisHostname:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-url'
  redisPort:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-port'
  secretName:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-serverless-secret-name'
  redisSG:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-security-group'

  # serverless plugins specific variables
  logRetentionInDays: 30
  apiStageTags:
    Owner: ${self:custom.vars.Owner}
    Description: ${self:custom.vars.Description}
    Name: ${self:custom.project}-${self:custom.function}-lambda
    Function: Serverless
    Environment: ${self:custom.environment}
    Product: ${self:custom.vars.Product}
    Resource: DRX
  apigwBinary:
    types: #list of mime-types
      - '*/*'
  prune:
    automatic: true
    number: 3
  associateWaf:
    name: ${self:custom.APIGWAFV2}
    version: V2
provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.region}
  vpc:
    securityGroupIds:
      - ${self:custom.redisSG}
    subnetIds: ${self:custom.infoVars.subnets}
  # versionFunctions: false
  endpointType: regional
  stage: ${self:custom.stage}
  deploymentBucket:
    name: ${self:custom.deploy_bucket} # Deployment bucket name. Default is generated by the framework
    serverSideEncryption: AES256 # when using server-side encryption
  memorySize: 512
  timeout: 20
  logs:
    restApi:
      roleManagedExternally: true
      role: ${self:custom.cloudWatchRole}
  stackTags:
    Owner: ${self:custom.vars.Owner}
    project: ${self:custom.project}
    Resource: DRX
  tags:
    Description: ${self:custom.vars.Description}
    Name: '${self:custom.project}-${self:custom.function}'
    Function: 'Serverless'
    Environment: ${self:custom.environment}
    Product: ${self:custom.vars.Product}
    buildNumber: ${self:custom.buildNumber}
  tracing:
    apiGateway: true
    lambda: true

  apiGateway:
    disableDefaultEndpoint: true

plugins:
  # - serverless-plugin-bind-deployment-id
  - serverless-plugin-optimize
  - api-gateway-stage-tag-plugin
  - serverless-plugin-log-retention
  - serverless-prune-plugin
  - serverless-associate-waf

  # - serverless-pseudo-parameters
  # - ./serverless-plugin/metric

package: # Optional deployment packaging configuration
  individually: true
  include: # Specify the directories and files which should be included in the deployment package
    - src/**

functions:
  deleteCache:
    handler: src/handler.deleteCache
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      secretName: ${self:custom.secretName}
      redisPort: ${self:custom.redisPort}
      redisHostname: ${self:custom.redisHostname}
      environment: ${self:custom.environment}
      logLevel: ${self:custom.vars.logLevel}

    role: lambdaRole
    events:
      - http:
          path: /
          method: delete
          # RequestValidatorId: !Ref RequestValidator
          cors:
            origins: '*'
            method:
              - 'delete'
              - 'OPTIONS'
            # headers:
            #- Content-Type
            #- x-api-token
            #- X-Amz-Date
            #- Authorization
            #- X-Api-Key
            #- X-Amz-Security-Token
            #- authorizationtoken
  postTestRun:
    handler: src/handler.postTestRun
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      secretName: ${self:custom.secretName}
      redisPort: ${self:custom.redisPort}
      redisHostname: ${self:custom.redisHostname}
      environment: ${self:custom.environment}
      logLevel: ${self:custom.vars.logLevel}

    role: lambdaRole
    events:
      - http:
          path: /
          method: post
          # RequestValidatorId: !Ref RequestValidator
          cors:
            origins: '*'
            method:
              - 'post'
              - 'OPTIONS'
            # headers:
            #- Content-Type
            #- x-api-token
            #- X-Amz-Date
            #- Authorization
            #- X-Api-Key
            #- X-Amz-Security-Token
            #- authorizationtoken
## Resources ##
resources:
  Conditions:
    CreateAlarm:
      Fn::Equals:
        - ${self:custom.vars.createAlarms}
        - 'true'
  Resources:
    CustomDomainMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn:
        - 'ApiGatewayDeployment${sls:instanceId}'
      Properties:
        RestApiId: !Ref ApiGatewayRestApi
        BasePath: ${self:custom.customDomainPath}
        DomainName:
          ${self:custom.customDomainName}
          # 'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
        Stage: ${self:custom.stage}
    # RequestValidator:
    #   Type: AWS::ApiGateway::RequestValidator
    #   Properties:
    #     RestApiId: !Ref ApiGatewayRestApi
    #     ValidateRequestBody: true
    #     ValidateRequestParameters: false
    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /drx/all/
        PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/core/PermissionsBoundary'
        ManagedPolicyArns:
          [
            'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole',
            'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess',
          ]
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaDRX
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # Default Lambda Permissions for Cloudwatch Log Access
                  Resource: arn:aws:logs:${self:custom.region}:*:log-group:/aws/lambda/*:*:*
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                - Effect: Allow
                  Resource:
                    - arn:aws:ssm:${self:custom.region}:*:parameter/*
                  Action:
                    - ssm:GetParameter
                - Effect: Allow
                  Resource:
                    - arn:aws:secretsmanager:${self:custom.region}:*:*
                  Action:
                    - secretsmanager:GetSecretValue
    # warmupRole:
    #   Type: AWS::IAM::Role
    #   Properties:
    #     Path: /authnz/all/
    #     ManagedPolicyArns: [
    #         "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole",
    #       ] ## Allows VPC Execution rights for Lambda
    #     AssumeRolePolicyDocument:
    #       Version: "2012-10-17"
    #       Statement:
    #         - Effect: Allow
    #           Principal:
    #             Service:
    #               - lambda.amazonaws.com
    #           Action: sts:AssumeRole
    #     Policies:
    #       - PolicyName: LambdaWarmupAuthnz
    #         PolicyDocument:
    #           Version: "2012-10-17"
    #           Statement:
    #             - Effect: Allow # WarmUp lambda to send logs to CloudWatch
    #               Action:
    #                 - logs:CreateLogGroup
    #                 - logs:CreateLogStream
    #                 - logs:PutLogEvents
    #               Resource:
    #                 - "Fn::Join":
    #                     - ":"
    #                     - - "arn:aws:logs"
    #                       - Ref: "AWS::Region"
    #                       - Ref: "AWS::AccountId"
    #                       - "log-group:/aws/lambda/*:*:*"
    #             - Effect: Allow # WarmUp lambda to manage ENIS (only needed if deploying to VPC, https://docs.aws.amazon.com/lambda/latest/dg/vpc.html)
    #               Action:
    #                 - ec2:CreateNetworkInterface
    #                 - ec2:DescribeNetworkInterfaces
    #                 - ec2:DetachNetworkInterface
    #                 - ec2:DeleteNetworkInterface
    #               Resource: "*"
    #             - Effect: "Allow" # WarmUp lambda to invoke the functions to be warmed
    #               Action:
    #                 - "lambda:InvokeFunction"
    #               Resource:
    #                 - Fn::Join:
    #                     - ":"
    #                     - - arn:aws:lambda
    #                       - Ref: AWS::Region
    #                       - Ref: AWS::AccountId
    #                       - function:${self:service}-${opt:stage, self:provider.stage}-*

  Outputs:
    RestApiId:
      Description: 'rest api id'
      Value:
        Ref: ApiGatewayRestApi
