template: 
  type: file
  path: secrets-manager.yaml

parameters:
  Description: DRX project serverless secrets manager
  Project: !environment_variable PROJECT_CODE
  Environment: {{ stack_group_config.environment }}
  # ProjectRolePattern: drx*

