service: '${self:custom.project}-${self:custom.function}-lambda'

custom:
  # project specific variables
  vars: ${file(./variables.json)}
  infoVars: ${file(./aws_infra_parameters.json)}
  resourceVars: ${file(./aws_resource_parameters.json)}
  commonVars: ${file(./lambda_common_env_parameters.json)}
  region: ${env:AWS_REGION}
  environment: ${env:ENVIRONMENT}
  stage: ${env:ENVIRONMENT}
  buildNumber: ${env:CI_PIPELINE_IID}
  project: ${env:PROJECT_CODE}
  function: service-requests
  APIGWAFV2: ${self:custom.resourceVars.apiWafv2}
  kmsArn:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-kms-arn'
  customDomainName:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
  customDomainPath: !Sub ${env:PROVIDER}-${self:custom.vars.releaseVersion}
  apiauthorizerArn:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-apiauthorizer'
  deploy_bucket: ${env:DEPLOY_S3_BUCKET}
  cloudWatchRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/cochlear-general-apigateway-log-role'
  secretName:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-serverless-secret-name'
  redisHostname:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-url'
  redisPort:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-port'
  redisSG:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-security-group'
  # serverless plugins specific variables

  logRetentionInDays: 30
  apiStageTags:
    Owner: ${self:custom.vars.Owner}
    Description: ${self:custom.vars.Description}
    Name: ${self:custom.project}-${self:custom.function}-lambda
    Function: Serverless
    Environment: ${self:custom.vars.Environment}
    Product: ${self:custom.vars.Product}
    Resource: DRX
  apigwBinary:
    types: # list of mime-types
      - '*/*'
  prune:
    automatic: true
    number: 3
  associateWaf:
    name: ${self:custom.APIGWAFV2}
    version: V2
  metrics:
    - name: AWSSecretFail
      pattern: '{($.reason="AWS_SECRET_MANGERMENT_FAIL") && ($.result="ERROR")}'
      functions:
        - getUserInfo
      namespace: ${self:custom.commonVars.cloudWatchNameSpace}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.region}
  vpc:
    securityGroupIds:
      - ${self:custom.redisSG}
    subnetIds: ${self:custom.infoVars.subnets}
  endpointType: regional
  stage: ${self:custom.stage}
  deploymentBucket:
    name: ${self:custom.deploy_bucket} # Deployment bucket name. Default is generated by the framework
    serverSideEncryption: AES256 # when using server-side encryption
  memorySize: 512
  timeout: 25
  logs:
    restApi:
      roleManagedExternally: true
      role: ${self:custom.cloudWatchRole}
  stackTags:
    Owner: ${self:custom.vars.Owner}
    project: ${self:custom.project}
    Resource: DRX
  tags:
    Description: ${self:custom.vars.Description}
    Name: '${self:custom.project}-${self:custom.function}'
    Function: 'Serverless'
    Environment: ${self:custom.environment}
    Product: ${self:custom.vars.Product}
    buildNumber: ${self:custom.buildNumber}
  tracing:
    apiGateway: true
    lambda: true
  apiGateway:
    disableDefaultEndpoint: true
  environment:
    AWS_APPCONFIG_EXTENSION_POLL_INTERVAL_SECONDS: 30
    AWS_APPCONFIG_EXTENSION_POLL_TIMEOUT_MILLIS: 3000
    AWS_APPCONFIG_EXTENSION_HTTP_PORT: 2772

plugins:
  - serverless-plugin-optimize
  - api-gateway-stage-tag-plugin
  - serverless-plugin-log-retention
  - serverless-prune-plugin
  - ./serverless-plugin/metric
  - serverless-associate-waf

package: # Optional deployment packaging configuration
  individually: true
  include: # Specify the directories and files which should be included in the deployment package
    - src/**

functions:
  CorsServiceRequestsFunction:
    handler: src/cors-handler.handleRequest
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      corsAllowedHeaders: ${self:custom.commonVars.corsAllowedHeaders}
      corsAllowedMethods: ${self:custom.commonVars.corsGETPOSTAllowedMethods}
      corsOrigin: ${self:custom.commonVars.corsOrigin}
      corsMaxAge: ${self:custom.commonVars.corsMaxAge}
    role: lambdaRole
    events:
      - http:
          path: /
          method: OPTIONS
      - http:
          path: /{serviceRequestId}
          method: OPTIONS

  GetServiceRequests:
    handler: src/handler.getServiceRequests
    layers:
      - arn:aws:lambda:ap-southeast-2:080788657173:layer:AWS-AppConfig-Extension:91
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      boomiOauthEndpoint: ${self:custom.commonVars.boomiOauthEndpoint}
      boomiServiceEndpoint: ${self:custom.commonVars.boomiServiceEndpoint}
      Environment: ${self:custom.environment}
      PMEndpoint: ${self:custom.vars.pmEndpoint}
      SCEndpoint: ${self:custom.commonVars.scEndpoint}
      SFHostname: ${self:custom.commonVars.sfHostname}
      SFClientID: ${self:custom.commonVars.sfClientID}
      SFUsername: ${self:custom.commonVars.sfUsername}
      SMSFIntegration: ${self:custom.secretName}
      RedisPort: ${self:custom.redisPort}
      RedisHostname: ${self:custom.redisHostname}
      userSessionSeconds: ${self:custom.vars.userSessionSeconds}
      tokenSessionSeconds: ${self:custom.vars.tokenSessionSeconds}
      redisTokenKey: ${self:custom.commonVars.redisTokenKey}
      userSessionPrefix: ${self:custom.commonVars.userSessionPrefix}
      releaseVersion: ${self:custom.vars.releaseVersion}
      logLevel: ${self:custom.vars.logLevel}
      appConfigApplicationId: ${self:custom.vars.appConfigApplicationId}
      appConfigEnvironmentId: ${self:custom.vars.appConfigEnvironmentId}
      appConfigUrl: ${self:custom.vars.appConfigUrl}
    role: lambdaRole
    events:
      - http:
          path: /
          method: GET
          cors:
            origins: '*'
            headers:
              - Content-Type
              - x-api-token
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - authorizationtoken
            allowCredentials: false
          authorizer:
            name: authorizer
            arn: ${self:custom.apiauthorizerArn}
            type: request
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization, method.request.querystring.id

  GetServiceRequest:
    handler: src/handler.getServiceRequest
    layers:
      - arn:aws:lambda:ap-southeast-2:080788657173:layer:AWS-AppConfig-Extension:91
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      boomiOauthEndpoint: ${self:custom.commonVars.boomiOauthEndpoint}
      boomiServiceEndpoint: ${self:custom.commonVars.boomiServiceEndpoint}
      Environment: ${self:custom.environment}
      PMEndpoint: ${self:custom.vars.pmEndpoint}
      SCEndpoint: ${self:custom.commonVars.scEndpoint}
      SFHostname: ${self:custom.commonVars.sfHostname}
      SFClientID: ${self:custom.commonVars.sfClientID}
      SFUsername: ${self:custom.commonVars.sfUsername}
      SMSFIntegration: ${self:custom.secretName}
      RedisPort: ${self:custom.redisPort}
      RedisHostname: ${self:custom.redisHostname}
      userSessionSeconds: ${self:custom.vars.userSessionSeconds}
      tokenSessionSeconds: ${self:custom.vars.tokenSessionSeconds}
      redisTokenKey: ${self:custom.commonVars.redisTokenKey}
      userSessionPrefix: ${self:custom.commonVars.userSessionPrefix}
      releaseVersion: ${self:custom.vars.releaseVersion}
      logLevel: ${self:custom.vars.logLevel}
      appConfigApplicationId: ${self:custom.vars.appConfigApplicationId}
      appConfigEnvironmentId: ${self:custom.vars.appConfigEnvironmentId}
      appConfigUrl: ${self:custom.vars.appConfigUrl}
    role: lambdaRole
    events:
      - http:
          path: /{serviceRequestId}
          method: GET
          cors:
            origins: '*'
            headers:
              - Content-Type
              - x-api-token
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - authorizationtoken
            allowCredentials: false
          authorizer:
            name: authorizer
            arn: ${self:custom.apiauthorizerArn}
            type: request
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization, method.request.querystring.id

  RaiseServiceRequest:
    handler: src/handler.raiseServiceRequest
    layers:
      - arn:aws:lambda:ap-southeast-2:080788657173:layer:AWS-AppConfig-Extension:91
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      boomiOauthEndpoint: ${self:custom.commonVars.boomiOauthEndpoint}
      boomiServiceEndpoint: ${self:custom.commonVars.boomiServiceEndpoint}
      Environment: ${self:custom.environment}
      PMEndpoint: ${self:custom.vars.pmEndpoint}
      SCEndpoint: ${self:custom.commonVars.scEndpoint}
      SFHostname: ${self:custom.commonVars.sfHostname}
      SFClientID: ${self:custom.commonVars.sfClientID}
      SFUsername: ${self:custom.commonVars.sfUsername}
      SMSFIntegration: ${self:custom.secretName}
      RedisPort: ${self:custom.redisPort}
      RedisHostname: ${self:custom.redisHostname}
      userSessionSeconds: ${self:custom.vars.userSessionSeconds}
      tokenSessionSeconds: ${self:custom.vars.tokenSessionSeconds}
      redisTokenKey: ${self:custom.commonVars.redisTokenKey}
      userSessionPrefix: ${self:custom.commonVars.userSessionPrefix}
      releaseVersion: ${self:custom.vars.releaseVersion}
      logLevel: ${self:custom.vars.logLevel}
      appConfigApplicationId: ${self:custom.vars.appConfigApplicationId}
      appConfigEnvironmentId: ${self:custom.vars.appConfigEnvironmentId}
      appConfigUrl: ${self:custom.vars.appConfigUrl}
    role: lambdaRole
    events:
      - http:
          path: /
          method: POST
          cors:
            origins: '*'
            headers:
              - Content-Type
              - x-api-token
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - authorizationtoken
            allowCredentials: false
          authorizer:
            name: authorizer
            arn: ${self:custom.apiauthorizerArn}
            type: request
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization, method.request.querystring.id

## Resources ##
resources:
  Conditions:
    CreateAlarm:
      Fn::Equals:
        - ${self:custom.vars.createAlarms}
        - 'true'

  Resources:
    CustomDomainMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn:
        - 'ApiGatewayDeployment${sls:instanceId}'
      Properties:
        RestApiId: !Ref ApiGatewayRestApi
        BasePath: ${self:custom.customDomainPath}
        DomainName:
          ${self:custom.customDomainName}
          # 'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
        Stage: ${self:custom.stage}

    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    GetServiceRequestsLambdaFunctionErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Condition: CreateAlarm
      Properties:
        AlarmActions:
          - ${self:custom.commonVars.alarmSNS}
        AlarmDescription: 'DRX lambda fail'
        AlarmName: !Join
          - '-'
          - - 'DRX-lambda-GetServiceRequests-fail'
            - ${self:custom.stage}
            # - ${opt:versionNumber,"0"}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: '1'
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Ref GetServiceRequestsLambdaFunction
        Period: '60'
        Statistic: Sum
        Threshold: '1'
        TreatMissingData: 'notBreaching'
        OKActions:
          - ${self:custom.commonVars.alarmSNS}

    GetServiceRequestLambdaFunctionErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Condition: CreateAlarm
      Properties:
        AlarmActions:
          - ${self:custom.commonVars.alarmSNS}
        AlarmDescription: 'DRX lambda fail'
        AlarmName: !Join
          - '-'
          - - 'DRX-lambda-GetServiceRequest-fail'
            - ${self:custom.stage}
            # - ${opt:versionNumber,"0"}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: '1'
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Ref GetServiceRequestLambdaFunction
        Period: '60'
        Statistic: Sum
        Threshold: '1'
        TreatMissingData: 'notBreaching'
        OKActions:
          - ${self:custom.commonVars.alarmSNS}

    RaiseServiceRequestLambdaFunctionErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Condition: CreateAlarm
      Properties:
        AlarmActions:
          - ${self:custom.commonVars.alarmSNS}
        AlarmDescription: 'DRX lambda fail'
        AlarmName: !Join
          - '-'
          - - 'DRX-lambda-RaiseServiceRequest-fail'
            - ${self:custom.stage}
            # - ${opt:versionNumber,"0"}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: '1'
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Ref RaiseServiceRequestLambdaFunction
        Period: '60'
        Statistic: Sum
        Threshold: '1'
        TreatMissingData: 'notBreaching'
        OKActions:
          - ${self:custom.commonVars.alarmSNS}

    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /drx/all/
        PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/core/PermissionsBoundary'
        ManagedPolicyArns:
          [
            'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole',
            'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
          ]
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaDRX
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Resource: arn:aws:logs:${self:custom.region}:*:log-group:/aws/lambda/*:*:*
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                - Effect: Allow
                  Resource:
                    - arn:aws:ssm:${self:custom.region}:*:parameter/*
                  Action:
                    - ssm:GetParameter
                - Effect: Allow
                  Resource:
                    - arn:aws:secretsmanager:${self:custom.region}:*:*
                  Action:
                    - secretsmanager:GetSecretValue
                - Effect: 'Allow'
                  Resource:
                    - !Sub
                      - 'arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/${ApplicationId}/environment/${EnvironmentId}/configuration/*'
                      - ApplicationId: ${self:custom.vars.appConfigApplicationId}
                        EnvironmentId: ${self:custom.vars.appConfigEnvironmentId}
                  Action:
                    - appconfig:GetLatestConfiguration
                    - appconfig:StartConfigurationSession

  Outputs:
    RestApiId:
      Description: 'rest api id'
      Value:
        Ref: ApiGatewayRestApi
