service: 'cochlear-${self:custom.project}-${self:custom.function}'

custom:
  # project specific variables
  alias: V1
  vars: ${file(./variables.json)}
  infoVars: ${file(./aws_infra_parameters.json)}
  resourceVars: ${file(./aws_resource_parameters.json)}
  commonVars: ${file(./lambda_common_env_parameters.json)}
  region: ${env:AWS_REGION}
  environment: ${env:ENVIRONMENT}
  stage: ${env:ENVIRONMENT}
  buildNumber: ${env:CI_PIPELINE_IID}
  project: ${env:PROJECT_CODE}
  function: apiauthorizer
  kmsArn:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-kms-arn'
  secretName:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-serverless-secret-name'
  redisHostname:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-url'
  redisPort:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-port'
  redisSG:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-security-group'
  # customDomainName:
  #   'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
  # customDomainPath: !Sub ${env:PROVIDER}-${self:custom.vars.releaseVersion}
  # apiauthorizerArn:
  #   'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-apiauthorizer'
  deploy_bucket: ${env:DEPLOY_S3_BUCKET}
  cloudWatchRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/cochlear-general-apigateway-log-role'

  # serverless plugins specific variables
  logRetentionInDays: 30
  prune:
    automatic: true
    number: 3
  metrics:
    - name: functionExecution
      pattern: '{($.reason="API_AUTHORIZER_START") && ($.result="RECORD")}'
      functions:
        - authorizer
      namespace: ${self:custom.commonVars.cloudWatchNameSpace}

  deploymentSettings:
    codeDeployRolePermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/core/PermissionsBoundary'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.region}
  vpc:
    securityGroupIds:
      - ${self:custom.redisSG}
    subnetIds: ${self:custom.infoVars.subnets}
  endpointType: regional
  stage: ${self:custom.stage}
  deploymentBucket:
    name: ${self:custom.deploy_bucket} # Deployment bucket name. Default is generated by the framework
    serverSideEncryption: AES256 # when using server-side encryption
  memorySize: 512
  timeout: 20
  logs:
    restApi:
      roleManagedExternally: true
      role: ${self:custom.cloudWatchRole}
  stackTags:
    Owner: ${self:custom.vars.Owner}
    project: ${self:custom.project}
    Resource: DRX
  tags:
    Description: ${self:custom.vars.Description}
    Name: '${self:custom.project}-${self:custom.function}'
    Function: 'Serverless'
    Environment: ${self:custom.environment}
    Product: ${self:custom.vars.Product}
    buildNumber: ${self:custom.buildNumber}
  tracing:
    apiGateway: true
    lambda: true

plugins:
  - serverless-plugin-canary-deployments
  - serverless-plugin-optimize
  - serverless-plugin-log-retention
  - serverless-prune-plugin

package: # Optional deployment packaging configuration
  individually: true
  include: # Specify the directories and files which should be included in the deployment package
    - src/**

functions:
  authorizer:
    handler: src/handler.authenticate
    kmsKeyArn: ${self:custom.kmsArn}
    name: cochlear-drx-apiauthorizer-${self:custom.stage}
    environment:
      region: ${self:custom.region}
      Environment: ${self:custom.environment}
      secretName: ${self:custom.secretName}
      RedisPort: ${self:custom.redisPort}
      RedisHostname: ${self:custom.redisHostname}
      publicKey: ${self:custom.vars.publicKey}
      userSessionSeconds: ${self:custom.vars.userSessionSeconds}
      userSessionPrefix: ${self:custom.commonVars.userSessionPrefix}
      logLevel: ${self:custom.vars.logLevel}
      auth0Host: ${self:custom.vars.auth0Host}
      auth0ClientId: ${self:custom.vars.auth0ClientId}
      auth0Audience: ${self:custom.vars.auth0Audience}
    role: lambdaRole
    deploymentSettings:
      type: AllAtOnce
      alias: ${self:custom.alias}

## Resources ##
resources:
  Resources:
    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /drx/all/
        PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/core/PermissionsBoundary'
        ManagedPolicyArns:
          [
            'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole',
            'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
          ]
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaDRX
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # Default Lambda Permissions for Cloudwatch Log Access
                  Resource: arn:aws:logs:${self:custom.region}:*:log-group:/aws/lambda/*:*:*
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                - Effect: Allow
                  Resource:
                    - arn:aws:ssm:${self:custom.region}:*:parameter/*
                  Action:
                    - ssm:GetParameter
                - Effect: Allow
                  Resource:
                    - arn:aws:secretsmanager:${self:custom.region}:*:*
                  Action:
                    - secretsmanager:GetSecretValue
                - Effect: 'Allow' # lambda to invoke the functions
                  Action:
                    - 'lambda:InvokeFunction'
                  Resource:
                    - !Sub 'arn:aws:lambda:${self:custom.region}:${AWS::AccountId}:function:*'
                    # - Fn::Join:
                    #     - ':'
                    #     - - arn:aws:lambda
                    #       - Ref: AWS::Region
                    #       - Ref: AWS::AccountId
                    #       - function:*
                    #       - function:${self:service}-${opt:stage, self:provider.stage}-*
    # warmupRole:
    #   Type: AWS::IAM::Role
    #   Properties:
    #     Path: /drx/all/
    #     ManagedPolicyArns: [
    #         'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole',
    #       ] ## Allows VPC Execution rights for Lambda
    #     AssumeRolePolicyDocument:
    #       Version: '2012-10-17'
    #       Statement:
    #         - Effect: Allow
    #           Principal:
    #             Service:
    #               - lambda.amazonaws.com
    #           Action: sts:AssumeRole
    #     Policies:
    #       - PolicyName: LambdaWarmupDRX
    #         PolicyDocument:
    #           Version: '2012-10-17'
    #           Statement:
    #             - Effect: Allow # WarmUp lambda to send logs to CloudWatch
    #               Action:
    #                 - logs:CreateLogGroup
    #                 - logs:CreateLogStream
    #                 - logs:PutLogEvents
    #               Resource:
    #                 - 'Fn::Join':
    #                     - ':'
    #                     - - 'arn:aws:logs'
    #                       - Ref: 'AWS::Region'
    #                       - Ref: 'AWS::AccountId'
    #                       - 'log-group:/aws/lambda/*:*:*'
    #             - Effect: Allow # WarmUp lambda to manage ENIS (only needed if deploying to VPC, https://docs.aws.amazon.com/lambda/latest/dg/vpc.html)
    #               Action:
    #                 - ec2:CreateNetworkInterface
    #                 - ec2:DescribeNetworkInterfaces
    #                 - ec2:DetachNetworkInterface
    #                 - ec2:DeleteNetworkInterface
    #               Resource: '*'
    #             - Effect: 'Allow' # WarmUp lamda to invoke the functions to be warmed
    #               Action:
    #                 - 'lambda:InvokeFunction'
    #               Resource:
    #                 - Fn::Join:
    #                     - ':'
    #                     - - arn:aws:lambda
    #                       - Ref: AWS::Region
    #                       - Ref: AWS::AccountId
    #                       - function:${self:service}-${opt:stage, self:provider.stage}-*
  Outputs:
    AuthorizerLambdaFunctionAliasV1:
      Value:
        Ref: AuthorizerLambdaFunctionAliasV1
      Export:
        Name: !Sub '${env:PROJECT_CODE}-${env:ENVIRONMENT}-apiauthorizer'
