service: '${self:custom.project}-${self:custom.function}-lambda'

custom:
  # project specific variables
  vars: ${file(./variables.json)}
  infoVars: ${file(./aws_infra_parameters.json)}
  resourceVars: ${file(./aws_resource_parameters.json)}
  commonVars: ${file(./lambda_common_env_parameters.json)}
  region: ${env:AWS_REGION}
  environment: ${env:ENVIRONMENT}
  stage: ${env:ENVIRONMENT}
  buildNumber: ${env:CI_PIPELINE_IID}
  project: ${env:PROJECT_CODE}
  APIGWAFV2: ${self:custom.resourceVars.apiWafv2}
  function: header-footer
  kmsArn:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-kms-arn'
  customDomainName:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
  customDomainPath: !Sub ${env:PROVIDER}-${self:custom.vars.releaseVersion}
  apiauthorizerArn:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-apiauthorizer'
  deploy_bucket: ${env:DEPLOY_S3_BUCKET}
  cloudWatchRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/cochlear-general-apigateway-log-role'
  redisHostname:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-url'
  redisPort:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-port'
  secretName:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-serverless-secret-name'
  redisSG:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-security-group'

  proxyNamePath: '/header-footer-V1'
  proxyPrefixPath: '/v1/contents/header-footer'

  # serverless plugins specific variables
  logRetentionInDays: 30
  apiStageTags:
    Owner: ${self:custom.vars.Owner}
    Description: ${self:custom.vars.Description}
    Name: ${self:custom.project}-${self:custom.function}-lambda
    Function: Serverless
    Environment: ${self:custom.environment}
    Product: ${self:custom.vars.Product}
    Resource: DRX
  apigwBinary:
    types: #list of mime-types
      - '*/*'
  prune:
    automatic: true
    number: 3
  associateWaf:
    name: ${self:custom.APIGWAFV2}
    version: V2

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.region}
  vpc:
    securityGroupIds:
      - ${self:custom.redisSG}
    subnetIds: ${self:custom.infoVars.subnets}
  endpointType: regional
  stage: ${self:custom.stage}
  deploymentBucket:
    name: ${self:custom.deploy_bucket} # Deployment bucket name. Default is generated by the framework
    serverSideEncryption: AES256 # when using server-side encryption
  memorySize: 512
  timeout: 20
  logs:
    restApi:
      roleManagedExternally: true
      role: ${self:custom.cloudWatchRole}
  stackTags:
    Owner: ${self:custom.vars.Owner}
    project: ${self:custom.project}
    Resource: DRX
  tags:
    Description: ${self:custom.vars.Description}
    Name: '${self:custom.project}-${self:custom.function}'
    Function: 'Serverless'
    Environment: ${self:custom.environment}
    Product: ${self:custom.vars.Product}
    buildNumber: ${self:custom.buildNumber}
  tracing:
    apiGateway: true
    lambda: true

plugins:
  - serverless-plugin-optimize
  - api-gateway-stage-tag-plugin
  - serverless-plugin-log-retention
  - ./serverless-plugin/metric
  - serverless-prune-plugin
  - serverless-associate-waf

package: # Optional deployment packaging configuration
  individually: true
  include: # Specify the directories and files which should be included in the deployment package
    - src/**

functions:
  CorsHeaderFooterFunction:
    handler: src/cors-handler.handleRequest
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      corsAllowedHeaders: ${self:custom.commonVars.corsAllowedHeaders}
      corsAllowedMethods: ${self:custom.commonVars.corsGETAllowedMethods}
      corsOrigin: ${self:custom.commonVars.corsOrigin}
      corsMaxAge: ${self:custom.commonVars.corsMaxAge}
    role: lambdaRole
    events:
      - http:
          path: /
          method: OPTIONS
  headerFooter:
    handler: src/handler.getHeaderFooter
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      secretName: ${self:custom.secretName}
      RedisPort: ${self:custom.redisPort}
      RedisHostname: ${self:custom.redisHostname}
      Environment: ${self:custom.environment}
      logLevel: ${self:custom.vars.logLevel}
      scApiKey: ${self:custom.vars.scApiKey}
      scEndpoint: ${self:custom.commonVars.scEndpoint}
      cacheSeconds: ${self:custom.vars.cacheSeconds}
      isScHttpAgent: ${self:custom.vars.isScHttpAgent}
    role: lambdaRole
    events:
      - http:
          path: /
          method: get
          cors:
            origins: '*'
            method:
              - 'GET'
              - 'OPTIONS'
            headers:
              - Content-Type
              - x-api-token
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - authorizationtoken

## Resources ##
resources:
  Conditions:
    CreateAlarm:
      Fn::Equals:
        - ${self:custom.vars.createAlarms}
        - 'true'
  Resources:
    CustomDomainMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn:
        - 'ApiGatewayDeployment${sls:instanceId}'
      Properties:
        RestApiId: !Ref ApiGatewayRestApi
        BasePath: ${self:custom.customDomainPath}
        DomainName:
          ${self:custom.customDomainName}
          # 'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
        Stage: ${self:custom.stage}
    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /drx/all/
        PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/core/PermissionsBoundary'
        ManagedPolicyArns:
          [
            'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole',
            'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'
          ]
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaDRX
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # Default Lambda Permissions for Cloudwatch Log Access
                  Resource: arn:aws:logs:${self:custom.region}:*:log-group:/aws/lambda/*:*:*
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                - Effect: Allow
                  Resource:
                    - arn:aws:ssm:${self:custom.region}:*:parameter/*
                  Action:
                    - ssm:GetParameter
                - Effect: Allow
                  Resource:
                    - arn:aws:secretsmanager:${self:custom.region}:*:*
                  Action:
                    - secretsmanager:GetSecretValue

  Outputs:
    RestApiId:
      Description: 'rest api id'
      Value:
        Ref: ApiGatewayRestApi
